#!/bin/bash

#default values
japaneseMode=0
originalDir=$(pwd)
temp=""
imageDir=""
cover=""


#options
while getopts "c:ij" opt; do
	case $opt in
 		j) japaneseMode=1 ;;
 	     	i) imageDir="ordered_images" ;;
		c) cover="$originalDir/$OPTARG" ;;
		*)
        	exit 1
        	;;
   	esac
done

shift $((OPTIND - 1))

filename="${!#}"

if [ $japaneseMode -eq 1 ]; then
	echo "ほう… 向かってくるのか…　逃げずにこのソフトに近づいてくるのか…"
fi

echo "Making working directory"
mkdir -p .working_$$

temp="${filename%.epub}.zip"

cp -f "$filename" ".working_$$/${filename%.epub}.zip"
filename="$temp"

cd ".working_$$" 

unzip -oq "$filename"

echo "copying images"
mkdir -p pics

if [ -n "$imageDir" ]; then
	echo "Reorganizing images"
	imageRenamer $(pwd)
fi

if [ -z "$imageDir" ]; then
	imageDir=$(find . -type d -name images)
fi

cp -f $imageDir/* pics/

cd pics

mkdir -p new

readarray -t fileList < <(find . -maxdepth 1 -type f \( -iname '*.jpeg' -o -iname '*.jpg' -o -iname '*.png' \) | sort -V | cut -c3-)
fileListLength=${#fileList[@]}

imageCount=1
barWidth=40

startNum=0

if [ -n "$cover" ]; then
	echo "This is the cover $cover"
fi

if [ -z "$cover" ]; then
	coverCheck=$(find "$originalDir/.working_$$/" -type f -iname cover.jpeg | head -n 1)
	if [ -n "$coverCheck" ]; then
		cover="$coverCheck"
	else
		cover="${fileList[0]}"
	fi
	startNum=1
fi

magick "$cover" "new/0.png"

echo "Working..."
 
for i in $(seq $startNum 2 $((fileListLength-1)))
do
	if [ $((i + 1)) -le $((fileListLength-1)) ]; then
		
		if [ "$japaneseMode" -eq 1 ]; then
			magick "${fileList[i+1]}" "${fileList[i]}" +append "new/${imageCount}.png"
		else
			magick "${fileList[i]}" "${fileList[i+1]}" +append "new/${imageCount}.png"
		fi
		imageCount=$((imageCount+1))

	else
		magick ${fileList[i]} new/${imageCount}.png
	fi

	percent=$(( (i + 1) * 100 / $fileListLength ))
    	filled=$((percent * barWidth / 100))
    	empty=$((barWidth - filled))
    	bar=$(printf "%0.s#" $(seq 1 $filled))
    	space=$(printf "%0.s-" $(seq 1 $empty))

    	printf "\r[%s%s] %3d%%" "$bar" "$space" "$percent"
done

bar=$(printf "%0.s#" $(seq 1 $barWidth))
printf "\r[%s] - 100%% Done!\n" "$bar"

if [ "$japaneseMode" -eq 1 ]; then
	
	echo "Reversing Image Order..."

	imageCount=$((imageCount+1))
	magick "$cover" "new/${imageCount}.png"
	
	readarray -t fileList < <(find new -maxdepth 1 -type f \( -name '*.jpeg' -o -name '*.jpg' -o -name '*.png' \) | sort -V)

	# Reverse the array
	for ((i=0, j=${#fileList[@]}-1; i<j; i++, j--)); do
    		tmp="tmp_$i"
    		mv "${fileList[i]}" "$tmp"             # move first to tmp
    		mv "${fileList[j]}" "${fileList[i]}"      # move last to first
    		mv "$tmp" "${fileList[j]}"             # move tmp to last

	done
fi

echo "Finishing up..."

filename=${filename%.zip}.cbz

zip -q "$filename" new/*


mkdir -p $originalDir/converted
mv "$filename" $originalDir/converted
cd $originalDir
rm -r .working_$$/*
rmdir  .working_$$

echo "Finished! Enjoy Reading :)"
